# Generated by Django 5.2.3 on 2025-08-05 06:13

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last update",
                        verbose_name="Last update",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date created",
                        verbose_name="Date created",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Announcement"), (1, "Update"), (2, "Info")],
                        default=0,
                        help_text="Post type",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            ("code", 2),
                            ("paragraph", 3),
                            ("video", 4),
                            ("image", 5),
                            ("quote", 6),
                            ("document", 7),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("bash", "Bash/Shell"),
                                        ("css", "CSS"),
                                        ("diff", "diff"),
                                        ("html", "HTML"),
                                        ("javascript", "Javascript"),
                                        ("json", "JSON"),
                                        ("python", "Python"),
                                        ("scss", "SCSS"),
                                        ("yaml", "YAML"),
                                    ],
                                    "help_text": "Coding language",
                                    "identifier": "language",
                                    "label": "Language",
                                },
                            ),
                            1: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"identifier": "code", "label": "Code"},
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("language", 0), ("code", 1)]],
                                {"help_text": "Code"},
                            ),
                            3: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Rich Text"},
                            ),
                            4: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"help_text": "Video"},
                            ),
                            5: (
                                "wagtail.images.blocks.ImageBlock",
                                [],
                                {"help_text": "Image"},
                            ),
                            6: (
                                "wagtail.blocks.BlockQuoteBlock",
                                (),
                                {"help_text": "Quote"},
                            ),
                            7: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"help_text": "Document"},
                            ),
                        },
                        help_text="Post content",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
