# Generated by Django 5.1 on 2025-01-01 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("answers", "0001_initial"),
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                help_text="Answer",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="questions.question",
            ),
        ),
    ]
