# Generated by Django 5.2 on 2025-05-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="description",
            field=models.CharField(
                help_text="Why the answer is correct or wrong", max_length=1024
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="text",
            field=models.CharField(help_text="Answer text", max_length=512),
        ),
    ]
