# Generated by Django 5.2 on 2025-06-02 09:42

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0003_alter_answer_description_alter_answer_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="description",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("paragraph", 1)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "name", "help_text": "Heading"},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Rich Text"}),
                },
                help_text="Why the answer is correct or wrong",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="is_correct",
            field=models.BooleanField(
                default=False, help_text="Designates if the answer is correct"
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="text",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("paragraph", 1)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "name", "help_text": "Heading"},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Rich Text"}),
                },
                help_text="Answer text",
            ),
        ),
    ]
