# Generated by Django 5.2 on 2025-05-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="order",
            field=models.SmallIntegerField(
                default=0, help_text="Module order in the course"
            ),
        ),
    ]
