# Generated by Django 5.2.3 on 2025-08-05 06:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last update",
                        verbose_name="Last update",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date created",
                        verbose_name="Date created",
                    ),
                ),
                (
                    "role",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Student"), (1, "Instructor")],
                        default=0,
                        help_text="Enrollment role",
                    ),
                ),
                (
                    "progress",
                    models.FloatField(
                        blank=True,
                        help_text="Course completion progress",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.0, "Progress must be >= 0."
                            ),
                            django.core.validators.MaxValueValidator(
                                100.0, "Progress must be <= 100."
                            ),
                        ],
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Designates weather the course is completed or not",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Enrolled Course",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="courses.course",
                    ),
                ),
            ],
        ),
    ]
