# Generated by Django 5.2.3 on 2025-08-05 06:13

import django.core.validators
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last update",
                        verbose_name="Last update",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date created",
                        verbose_name="Date created",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Quiz"), (1, "Text"), (2, "File Upload")],
                        default=0,
                        help_text="Assignment type",
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(help_text="Assignment description"),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [("code", 2), ("paragraph", 3)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("bash", "Bash/Shell"),
                                        ("css", "CSS"),
                                        ("diff", "diff"),
                                        ("html", "HTML"),
                                        ("javascript", "Javascript"),
                                        ("json", "JSON"),
                                        ("python", "Python"),
                                        ("scss", "SCSS"),
                                        ("yaml", "YAML"),
                                    ],
                                    "help_text": "Coding language",
                                    "identifier": "language",
                                    "label": "Language",
                                },
                            ),
                            1: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"identifier": "code", "label": "Code"},
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("language", 0), ("code", 1)]],
                                {"help_text": "Code"},
                            ),
                            3: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Rich Text"},
                            ),
                        },
                        help_text="Assignment instructions or more info",
                    ),
                ),
                (
                    "is_graded",
                    models.BooleanField(
                        default=True,
                        help_text="Designates if assignment is graded or for practice",
                    ),
                ),
                (
                    "is_auto_graded",
                    models.BooleanField(
                        default=True,
                        help_text="Designates if assignment is auto graded",
                    ),
                ),
                (
                    "question_count",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Max number of questions to display (Random Question Selection)",
                    ),
                ),
                (
                    "min_percentage",
                    models.FloatField(
                        default=80.0,
                        help_text="Minimum percentage to pass assignment",
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.0, "Min percentage must be greater than 0"
                            ),
                            django.core.validators.MaxValueValidator(
                                100.0, "Min percentage must be less than 100"
                            ),
                        ],
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True,
                        help_text="Designates if assignment is timed",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
