# Generated by Django 5.2.4 on 2025-08-06 06:04

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            ("code", 2),
                            ("paragraph", 3),
                            ("video", 4),
                            ("image", 5),
                            ("quote", 6),
                            ("document", 7),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("bash", "Bash/Shell"),
                                        ("css", "CSS"),
                                        ("diff", "diff"),
                                        ("html", "HTML"),
                                        ("javascript", "Javascript"),
                                        ("json", "JSON"),
                                        ("python", "Python"),
                                        ("scss", "SCSS"),
                                        ("yaml", "YAML"),
                                    ],
                                    "help_text": "Coding language",
                                    "identifier": "language",
                                    "label": "Language",
                                },
                            ),
                            1: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"identifier": "code", "label": "Code"},
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("language", 0), ("code", 1)]],
                                {"help_text": "Code"},
                            ),
                            3: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Rich Text"},
                            ),
                            4: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"help_text": "Video"},
                            ),
                            5: (
                                "wagtail.images.blocks.ImageBlock",
                                [],
                                {"help_text": "Image"},
                            ),
                            6: (
                                "wagtail.blocks.BlockQuoteBlock",
                                (),
                                {"help_text": "Quote"},
                            ),
                            7: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"help_text": "Document"},
                            ),
                        },
                        help_text="Page content",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            ("code", 2),
                            ("paragraph", 3),
                            ("video", 4),
                            ("image", 5),
                            ("quote", 6),
                            ("document", 7),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("bash", "Bash/Shell"),
                                        ("css", "CSS"),
                                        ("diff", "diff"),
                                        ("html", "HTML"),
                                        ("javascript", "Javascript"),
                                        ("json", "JSON"),
                                        ("python", "Python"),
                                        ("scss", "SCSS"),
                                        ("yaml", "YAML"),
                                    ],
                                    "help_text": "Coding language",
                                    "identifier": "language",
                                    "label": "Language",
                                },
                            ),
                            1: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"identifier": "code", "label": "Code"},
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("language", 0), ("code", 1)]],
                                {"help_text": "Code"},
                            ),
                            3: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Rich Text"},
                            ),
                            4: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"help_text": "Video"},
                            ),
                            5: (
                                "wagtail.images.blocks.ImageBlock",
                                [],
                                {"help_text": "Image"},
                            ),
                            6: (
                                "wagtail.blocks.BlockQuoteBlock",
                                (),
                                {"help_text": "Quote"},
                            ),
                            7: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"help_text": "Document"},
                            ),
                        },
                        help_text="Page content",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AddField(
            model_name="home",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("code", 2),
                    ("paragraph", 3),
                    ("video", 4),
                    ("image", 5),
                    ("quote", 6),
                    ("document", 7),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"identifier": "code", "label": "Code"},
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 0), ("code", 1)]],
                        {"help_text": "Code"},
                    ),
                    3: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Rich Text"}),
                    4: ("wagtail.embeds.blocks.EmbedBlock", (), {"help_text": "Video"}),
                    5: ("wagtail.images.blocks.ImageBlock", [], {"help_text": "Image"}),
                    6: ("wagtail.blocks.BlockQuoteBlock", (), {"help_text": "Quote"}),
                    7: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Document"},
                    ),
                },
                default="",
                help_text="Page content",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="home",
            name="headline",
            field=models.CharField(
                db_index=True, default="", help_text="Headline", max_length=128
            ),
            preserve_default=False,
        ),
    ]
