# Generated by Django 5.2 on 2025-05-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Category name",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        db_index=True, help_text="Category description", max_length=256
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
    ]
