# Generated by Django 5.2 on 2025-05-22 07:32

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "headline",
                    models.CharField(
                        db_index=True, help_text="Blog headline", max_length=128
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            ("paragraph", 0),
                            ("heading", 1),
                            ("image", 2),
                            ("document", 3),
                        ],
                        block_lookup={
                            0: ("wagtail.blocks.RichTextBlock", (), {}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"form_classname": "title"},
                            ),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {},
                            ),
                        },
                        help_text="Blog content",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog post",
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
