# Generated by Django 5.2 on 2025-05-28 19:23

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("paragraph", 1), ("image", 2), ("document", 3)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "help_text": "Heading"},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Rich Text"}),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Image"},
                    ),
                    3: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Document"},
                    ),
                },
                help_text="Blog content",
            ),
        ),
    ]
