# Generated by Django 5.1 on 2025-01-01 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Single Choice Quiz"), (1, "Multi Choice Quiz")],
                        default=0,
                        help_text="Question type",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        db_index=True, help_text="Question text", max_length=512
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        help_text="Question assignment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="assignments.assignment",
                    ),
                ),
            ],
        ),
    ]
