# Generated by Django 5.2 on 2025-06-02 09:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_question_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="text",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("paragraph", 1)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "name", "help_text": "Heading"},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Rich Text"}),
                },
                help_text="Question text",
            ),
        ),
    ]
