# Generated by Django 5.2 on 2025-05-22 07:32

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Course image", upload_to=" images/courses/"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Course name", max_length=64
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        db_index=True, help_text="Course headline", max_length=128
                    ),
                ),
                (
                    "rating",
                    models.FloatField(
                        blank=True, db_index=True, help_text="Course rating", null=True
                    ),
                ),
                (
                    "description",
                    wagtail.fields.StreamField(
                        [("paragraph", 0), ("heading", 1)],
                        block_lookup={
                            0: ("wagtail.blocks.RichTextBlock", (), {}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"form_classname": "title"},
                            ),
                        },
                        help_text="Item content",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Course category",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
