# Generated by Django 5.1 on 2024-10-09 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("paths", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(help_text="Image", upload_to="images/courses/"),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Name", max_length=64, unique=True
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        db_index=True, help_text="Headline", max_length=128
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        db_index=True, help_text="Description", max_length=256
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False, help_text="Designates if the course is approved"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "path",
                    models.ForeignKey(
                        blank=True,
                        help_text="Learning path",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="paths.path",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Instructor",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
