# Generated by Django 5.1 on 2025-01-01 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("departments", "0001_initial"),
        ("enrollments", "0002_initial"),
        ("specializations", "0001_initial"),
        ("tags", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_enrollments",
            field=models.ManyToManyField(
                help_text="Course enrollments",
                related_name="course_students",
                through="enrollments.Enrollment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                help_text="Course department",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="departments.department",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="specialization",
            field=models.ForeignKey(
                blank=True,
                help_text="Course specialization",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="specializations.specialization",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="tags",
            field=models.ManyToManyField(help_text="Course tags", to="tags.tag"),
        ),
        migrations.AddField(
            model_name="course",
            name="user",
            field=models.ForeignKey(
                help_text="Course instructor",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
