# Generated by Django 5.2 on 2025-05-23 06:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=wagtail.fields.StreamField(
                [("paragraph", 0), ("heading", 1)],
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: ("wagtail.blocks.CharBlock", (), {"form_classname": "title"}),
                },
                help_text="Course description",
            ),
        ),
    ]
