# Generated by Django 5.2 on 2025-05-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_course_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.DurationField(
                blank=True, help_text="Learning Path duration", null=True
            ),
        ),
    ]
