# Generated by Django 5.2 on 2025-05-29 09:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_course_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="prerequisites",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("paragraph", 1)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "help_text": "Heading"},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Rich Text"}),
                },
                help_text="Learning Path prerequisites",
                null=True,
            ),
        ),
    ]
