# Generated by Django 5.2 on 2025-05-22 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("paths", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="path",
            name="user",
            field=models.ForeignKey(
                help_text="Path instructor",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paths",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
