# Generated by Django 5.2 on 2025-05-28 19:25

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("courses", "0005_course_duration"),
        ("paths", "0002_initial"),
        ("tags", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="path",
            name="duration",
            field=models.DurationField(
                blank=True, help_text="Learning Path duration", null=True
            ),
        ),
        migrations.AddField(
            model_name="path",
            name="prerequisites",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("paragraph", 1)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "help_text": "Heading"},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Rich Text"}),
                },
                help_text="Learning Path prerequisites",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="path",
            name="category",
            field=models.ForeignKey(
                help_text="Learning Path category",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paths",
                to="categories.category",
            ),
        ),
        migrations.AlterField(
            model_name="path",
            name="courses",
            field=models.ManyToManyField(
                blank=True, help_text="Learning Path Courses", to="courses.course"
            ),
        ),
        migrations.AlterField(
            model_name="path",
            name="description",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("paragraph", 1)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "help_text": "Heading"},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Rich Text"}),
                },
                help_text="Learning Path description",
            ),
        ),
        migrations.AlterField(
            model_name="path",
            name="headline",
            field=models.CharField(
                db_index=True, help_text="Learning Path headline", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="path",
            name="image",
            field=models.ImageField(
                help_text="Learning Path image", upload_to="images/paths/"
            ),
        ),
        migrations.AlterField(
            model_name="path",
            name="name",
            field=models.CharField(
                db_index=True, help_text="Learning Path name", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="path",
            name="rating",
            field=models.FloatField(
                blank=True, db_index=True, help_text="Learning Path rating", null=True
            ),
        ),
        migrations.AlterField(
            model_name="path",
            name="tags",
            field=models.ManyToManyField(help_text="Learning Path tags", to="tags.tag"),
        ),
        migrations.AlterField(
            model_name="path",
            name="user",
            field=models.ForeignKey(
                help_text="Learning Path instructor",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paths",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
