# Generated by Django 5.2 on 2025-06-01 13:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paths", "0003_path_duration_path_prerequisites_alter_path_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="path",
            name="description",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("paragraph", 1)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "name", "help_text": "Heading"},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Rich Text"}),
                },
                help_text="Learning Path description",
            ),
        ),
        migrations.AlterField(
            model_name="path",
            name="prerequisites",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("paragraph", 1)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "name", "help_text": "Heading"},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Rich Text"}),
                },
                help_text="Learning Path prerequisites",
                null=True,
            ),
        ),
    ]
