# Generated by Django 5.2 on 2025-06-02 09:42

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paths", "0004_alter_path_description_alter_path_prerequisites"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="path",
            name="prerequisites",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("description", 1), ("prerequisites", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "name", "help_text": "Title"},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Description"},
                    ),
                    2: ("bayt_al_hikmah.ui.cms.blocks.PathChooserBlock", (), {}),
                    3: (
                        "wagtail.blocks.ListBlock",
                        (2,),
                        {"help_text": "Prerequisites"},
                    ),
                },
                help_text="Learning Path prerequisites",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="path",
            name="tags",
            field=models.ManyToManyField(
                blank=True, help_text="Learning Path tags", to="tags.tag"
            ),
        ),
    ]
