# Generated by Django 5.1 on 2025-01-01 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enrollments", "0001_initial"),
        ("specializations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="specialization",
            field=models.ForeignKey(
                blank=True,
                help_text="Enrolled Specialization",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="specializations.specialization",
            ),
        ),
    ]
