# Generated by Django 5.2 on 2025-05-28 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="is_completed",
            field=models.BooleanField(
                default=False,
                help_text="Designates weather the course is completed or not",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="progress",
            field=models.FloatField(
                blank=True,
                help_text="Course completion progress",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.0, "Progress must be >= 0."
                    ),
                    django.core.validators.MaxValueValidator(
                        100.0, "Progress must be <= 100."
                    ),
                ],
            ),
        ),
    ]
