# Generated by Django 5.2 on 2025-06-06 07:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "role",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Student"), (1, "Instructor")],
                        default=0,
                        help_text="Enrollment role",
                    ),
                ),
                (
                    "progress",
                    models.FloatField(
                        blank=True,
                        help_text="Course completion progress",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.0, "Progress must be >= 0."
                            ),
                            django.core.validators.MaxValueValidator(
                                100.0, "Progress must be <= 100."
                            ),
                        ],
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Designates weather the course is completed or not",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Enrolled Course",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="courses.course",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Enrolling User",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "course"), name="unique_course_enrollment"
                    )
                ],
            },
        ),
    ]
