# Generated by Django 5.2 on 2025-06-06 07:09

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assignments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Single Choice Quiz"), (1, "Multi Choice Quiz")],
                        default=0,
                        help_text="Question type",
                    ),
                ),
                (
                    "text",
                    wagtail.fields.StreamField(
                        [("heading", 0), ("paragraph", 1)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"form_classname": "title", "help_text": "Heading"},
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Rich Text"},
                            ),
                        },
                        help_text="Question text",
                    ),
                ),
                (
                    "assignment",
                    modelcluster.fields.ParentalKey(
                        help_text="Question assignment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="assignments.assignment",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Question owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
