# Generated by Django 5.2 on 2025-06-07 05:58

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Single Choice Quiz"), (1, "Multi Choice Quiz")],
                        default=0,
                        help_text="Question type",
                    ),
                ),
                ("text", wagtail.fields.RichTextField(help_text="Question text")),
                (
                    "assignment",
                    modelcluster.fields.ParentalKey(
                        help_text="Question assignment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="assignments.assignment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
