# Generated by Django 5.2.3 on 2025-08-05 06:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("answers", "0002_initial"),
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last update",
                        verbose_name="Last update",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date created",
                        verbose_name="Date created",
                    ),
                ),
                (
                    "grade",
                    models.FloatField(
                        blank=True,
                        help_text="Submission grade",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.0, "Grade must be >= 0."
                            ),
                            django.core.validators.MaxValueValidator(
                                100.0, "Grade must be <= 100."
                            ),
                        ],
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Submission file",
                        null=True,
                        upload_to="files/submissions/",
                    ),
                ),
                (
                    "answers",
                    models.ManyToManyField(
                        blank=True, help_text="Submission answers", to="answers.answer"
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        help_text="Submission assignment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="assignments.assignment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
