# Generated by Django 5.1 on 2025-01-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Faculty image", upload_to="images/faculties/"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Faculty name", max_length=64
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        db_index=True, help_text="Faculty headline", max_length=128
                    ),
                ),
                ("description", models.TextField(help_text="Faculty description")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
            ],
            options={
                "verbose_name_plural": "faculties",
            },
        ),
    ]
