# Generated by Django 5.1 on 2025-01-01 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, help_text="Assignment title", max_length=64
                    ),
                ),
                ("description", models.TextField(help_text="Assignment description")),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Assignment content", null=True
                    ),
                ),
                (
                    "is_manual",
                    models.BooleanField(
                        default=False,
                        help_text="Weather the assignment graded manually",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "lesson",
                    models.OneToOneField(
                        help_text="Assignment lesson",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lessons.lesson",
                    ),
                ),
            ],
        ),
    ]
