# Generated by Django 5.2 on 2025-05-22 07:32

import django.core.validators
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, help_text="Assignment title", max_length=64
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Assignment description", max_length=256
                    ),
                ),
                (
                    "question_count",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Max questions to display when using random questions",
                        null=True,
                    ),
                ),
                (
                    "min_percentage",
                    models.FloatField(
                        default=80.0,
                        help_text="Minimum percentage to pass the assignment",
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.0, "Min percentage must be greater than 0"
                            ),
                            django.core.validators.MaxValueValidator(
                                100.0, "Min percentage must be less than 100"
                            ),
                        ],
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [("paragraph", 0), ("heading", 1)],
                        block_lookup={
                            0: ("wagtail.blocks.RichTextBlock", (), {}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"form_classname": "title"},
                            ),
                        },
                        help_text="Item content",
                    ),
                ),
                (
                    "is_auto_graded",
                    models.BooleanField(
                        default=True,
                        help_text="Weather the assignment graded automatically",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
