# Generated by Django 5.1 on 2025-01-05 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="min_percentage",
            field=models.FloatField(
                default=80.0,
                help_text="Minimum percentage to pass the assignment",
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "Min percentage must be greater than 0"
                    ),
                    django.core.validators.MaxValueValidator(
                        100, "Min percentage must be less than 100"
                    ),
                ],
            ),
        ),
    ]
