# Generated by Django 5.2 on 2025-05-22 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assignments", "0001_initial"),
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="lesson",
            field=models.ForeignKey(
                help_text="Assignment lesson",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="lessons.lesson",
            ),
        ),
    ]
