# Generated by Django 5.2 on 2025-05-23 06:59

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="content",
            field=wagtail.fields.StreamField(
                [("paragraph", 0), ("heading", 1)],
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: ("wagtail.blocks.CharBlock", (), {"form_classname": "title"}),
                },
                help_text="Assignment instructions or more info",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="question_count",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Max number of questions to display (Random Question Selection)",
            ),
        ),
    ]
