# Generated by Django 5.2 on 2025-05-28 19:23

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_alter_assignment_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Quiz"), (1, "Text"), (2, "File Upload")],
                default=0,
                help_text="Assignment type",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="content",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("paragraph", 1)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "help_text": "Heading"},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Rich Text"}),
                },
                help_text="Assignment instructions or more info",
            ),
        ),
    ]
