# Generated by Django 5.2 on 2025-06-01 13:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0004_assignment_type_alter_assignment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="content",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("paragraph", 1)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "name", "help_text": "Heading"},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Rich Text"}),
                },
                help_text="Assignment instructions or more info",
            ),
        ),
    ]
