# Generated by Django 5.2 on 2025-06-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0005_alter_assignment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="is_auto_graded",
            field=models.BooleanField(
                default=True, help_text="Designates if the assignment is auto graded"
            ),
        ),
    ]
