# Generated by Django 5.2.3 on 2025-07-12 08:13

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningPath",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last update",
                        verbose_name="Last update",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date created",
                        verbose_name="Date created",
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        db_index=True,
                        help_text="Learning Path headline",
                        max_length=128,
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(help_text="Learning Path description"),
                ),
                (
                    "prerequisites",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Learning path prerequisites", null=True
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, help_text="Learning Path duration", null=True
                    ),
                ),
                (
                    "rating",
                    models.FloatField(
                        blank=True,
                        db_index=True,
                        help_text="Learning Path rating",
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        help_text="Learning Path image",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Learning path",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
