# Generated by Django 5.2.3 on 2025-07-12 08:13

import modelcluster.contrib.taggit
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("paths", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningpath",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="LearningPath tags",
                through="tags.LearningPathTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
