# Generated by Django 5.1 on 2025-01-01 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("faculties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Department image", upload_to="images/departments/"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Department name", max_length=64
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        db_index=True, help_text="Department headline", max_length=128
                    ),
                ),
                ("description", models.TextField(help_text="Department description")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        help_text="Department faculty",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="faculties.faculty",
                    ),
                ),
            ],
        ),
    ]
