# Generated by Django 5.2 on 2025-06-07 05:58

import django.core.validators
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        default=0, help_text="Item order in the collection"
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Quiz"), (1, "Text"), (2, "File Upload")],
                        default=0,
                        help_text="Assignment type",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Assignment description", max_length=256
                    ),
                ),
                (
                    "question_count",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Max number of questions to display (Random Question Selection)",
                    ),
                ),
                (
                    "min_percentage",
                    models.FloatField(
                        default=80.0,
                        help_text="Minimum percentage to pass the assignment",
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.0, "Min percentage must be greater than 0"
                            ),
                            django.core.validators.MaxValueValidator(
                                100.0, "Min percentage must be less than 100"
                            ),
                        ],
                    ),
                ),
                (
                    "content",
                    wagtail.fields.RichTextField(
                        help_text="Assignment instructions or more info"
                    ),
                ),
                (
                    "is_auto_graded",
                    models.BooleanField(
                        default=True,
                        help_text="Designates if the assignment is auto graded",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
