# Generated by Django 5.2 on 2025-06-07 05:58

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "headline",
                    models.CharField(
                        db_index=True, help_text="Course headline", max_length=128
                    ),
                ),
                (
                    "rating",
                    models.FloatField(
                        blank=True, db_index=True, help_text="Course rating", null=True
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(help_text="Course description"),
                ),
                (
                    "prerequisites",
                    wagtail.fields.StreamField(
                        [("heading", 0), ("description", 1), ("prerequisites", 3)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"form_classname": "title", "help_text": "Title"},
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Description"},
                            ),
                            2: ("how.ui.cms.blocks.CourseChooserBlock", (), {}),
                            3: (
                                "wagtail.blocks.ListBlock",
                                (2,),
                                {"help_text": "Required courses to be accomplished"},
                            ),
                        },
                        help_text="Course prerequisites",
                        null=True,
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, help_text="Course duration", null=True
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        help_text="Course image",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
