# Generated by Django 5.2 on 2025-06-06 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("enrollments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                help_text="Course enrollments",
                related_name="students",
                through="enrollments.Enrollment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
