# Generated by Django 5.2 on 2025-05-22 07:32

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, help_text="Post title", max_length=64
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            ("paragraph", 0),
                            ("heading", 1),
                            ("image", 2),
                            ("document", 3),
                        ],
                        block_lookup={
                            0: ("wagtail.blocks.RichTextBlock", (), {}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"form_classname": "title"},
                            ),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {},
                            ),
                        },
                        help_text="Post content",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Post course",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
