# Generated by Django 5.2 on 2025-05-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Announcement"), (1, "Update"), (2, "Info")],
                default=0,
                help_text="Assignment type",
            ),
        ),
    ]
