# Generated by Django 5.2.3 on 2025-07-12 08:13

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last update",
                        verbose_name="Last update",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date created",
                        verbose_name="Date created",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False, help_text="Designates if the answer is correct"
                    ),
                ),
                ("text", wagtail.fields.RichTextField(help_text="Answer text")),
                (
                    "feedback",
                    wagtail.fields.RichTextField(
                        help_text="Answer feedback to show after grading"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
