# Generated by Django 5.1 on 2025-01-01 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enrollments", "0003_initial"),
        ("specializations", "0001_initial"),
        ("tags", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="specialization",
            name="specialization_enrollments",
            field=models.ManyToManyField(
                help_text="Specialization enrollments",
                related_name="specialization_students",
                through="enrollments.Enrollment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="specialization",
            name="tags",
            field=models.ManyToManyField(
                help_text="Specialization tags", to="tags.tag"
            ),
        ),
        migrations.AddField(
            model_name="specialization",
            name="user",
            field=models.ForeignKey(
                help_text="Specialization instructor",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specializations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
