# Generated by Django 5.2 on 2025-06-03 13:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assignments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "grade",
                    models.FloatField(
                        blank=True,
                        help_text="Submission grade",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.0, "Grade must be >= 0."
                            ),
                            django.core.validators.MaxValueValidator(
                                100.0, "Grade must be <= 100."
                            ),
                        ],
                    ),
                ),
                ("answers", models.JSONField(help_text="Submission answers")),
                (
                    "feedback",
                    models.JSONField(
                        blank=True, help_text="Submission feedback", null=True
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Submission file",
                        null=True,
                        upload_to="files/submissions/",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        help_text="Submission assignment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="assignments.assignment",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
