# Generated by Django 5.1 on 2025-01-01 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("modules", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Lesson name", max_length=64
                    ),
                ),
                ("description", models.TextField(help_text="Lesson description")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "module",
                    models.ForeignKey(
                        help_text="Lesson module",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="modules.module",
                    ),
                ),
            ],
        ),
    ]
