# Generated by Django 5.2 on 2025-06-07 05:58

import modelcluster.contrib.taggit
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="Course tags",
                through="tags.ArticleTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
