# Generated by Django 5.1 on 2025-01-01 09:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, help_text="Item title", max_length=64
                    ),
                ),
                ("description", models.TextField(help_text="Item description")),
                (
                    "content",
                    models.TextField(blank=True, help_text="Item content", null=True),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Item file",
                        null=True,
                        upload_to="files/items/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["zip", "mp4", "pdf", "docx", "ppt"]
                            )
                        ],
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Video"),
                            (2, "Reading"),
                            (3, "Quiz"),
                            (4, "Practice Assignment"),
                            (5, "Graded Assignment"),
                        ],
                        help_text="Item type",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        help_text="Item lesson",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="lessons.lesson",
                    ),
                ),
            ],
        ),
    ]
