# Generated by Django 5.1 on 2024-10-09 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("modules", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(db_index=True, help_text="Title", max_length=64),
                ),
                (
                    "description",
                    models.CharField(
                        db_index=True, help_text="Description", max_length=256
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, help_text="Content", null=True),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Upload a file",
                        null=True,
                        upload_to="files/items/",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Video"),
                            (2, "Article"),
                            (3, "Quiz"),
                            (4, "Assignment"),
                        ],
                        help_text="Type",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "module",
                    models.ForeignKey(
                        help_text="Module",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules.module",
                    ),
                ),
            ],
        ),
    ]
