# Generated by Django 5.1 on 2024-10-10 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="course",
            field=models.ForeignKey(
                default=1,
                help_text="Course",
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Video"), (2, "Reading"), (3, "Quiz"), (4, "Assignment")],
                help_text="Type",
            ),
        ),
    ]
