# Generated by Django 5.1 on 2025-01-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Video"),
                    (2, "Reading"),
                    (3, "Quiz"),
                    (4, "Practice Assignment"),
                    (5, "Graded Assignment"),
                ],
                default=0,
                help_text="Item type",
            ),
        ),
    ]
