# Generated by Django 5.1 on 2025-01-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_alter_item_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Video"), (2, "Reading")], default=0, help_text="Item type"
            ),
        ),
    ]
