# Generated by Django 5.2.4 on 2025-08-06 06:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_categoryindex"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryindex",
            name="description",
            field=wagtail.fields.RichTextField(
                default="", help_text="Page description"
            ),
            preserve_default=False,
        ),
    ]
