name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install Dependencies
        run: |
          python -m venv .venv
          source .vevn/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Create a Django project and configure settings
        run: |
          source .vevn/bin/activate
          python -m django startproject mysite
          mv bayt_al_hikmah mysite
          cd mysite
          echo "AUTH_USER_MODEL = 'users.User'" >> mysite/settings.py
          echo "INSTALLED_APPS += ['bayt_al_hikmah', 'bayt_al_hikmah.courses', 'bayt_al_hikmah.institutes', 'bayt_al_hikmah.items', 'bayt_al_hikmah.modules', 'bayt_al_hikmah.specializations', 'bayt_al_hikmah.users', 'drf_redesign', 'rest_framework']" >> mysite/settings.py
          echo "from django.urls import include" >> mysite/urls.py
          echo "urlpatterns += [path('', include('bayt_al_hikmah.urls'))]" >> mysite/urls.py

      - name: Run Migrations, System checks and test
        run: |
          source .vevn/bin/activate
          cd mysite
          python manage.py migrate
          python manage.py check
          python manage.py test
