name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Django Project and configure settings
        run: |
          python -m django startproject mysite
          mv bayt_al_hikmah mysite
          cd mysite
          echo "INSTALLED_APPS += ['learn', 'bayt_al_hikmah.courses', 'bayt_al_hikmah.items', 'bayt_al_hikmah.modules', 'bayt_al_hikmah.paths', 'bayt_al_hikmah.users', 'drf_redesign', 'rest_framework']" >> mysite/settings.py
          echo "AUTH_USER_MODEL = 'users.User'" >> mysite/settings.py
          echo "from django.urls import include" >> mysite/urls.py
          echo "urlpatterns += [path('', include('bayt_al_hikmah.urls'))]" >> mysite/urls.py

      - name: Run Migrations
        run: |
          cd mysite
          python manage.py migrate
          python manage.py check
          python manage.py test
