# Generated by Django 5.2.3 on 2025-08-05 06:13

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last update",
                        verbose_name="Last update",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date created",
                        verbose_name="Date created",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Single Choice Quiz"), (1, "Multi Choice Quiz")],
                        default=0,
                        help_text="Question type",
                    ),
                ),
                (
                    "text",
                    wagtail.fields.StreamField(
                        [("code", 2), ("paragraph", 3)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("bash", "Bash/Shell"),
                                        ("css", "CSS"),
                                        ("diff", "diff"),
                                        ("html", "HTML"),
                                        ("javascript", "Javascript"),
                                        ("json", "JSON"),
                                        ("python", "Python"),
                                        ("scss", "SCSS"),
                                        ("yaml", "YAML"),
                                    ],
                                    "help_text": "Coding language",
                                    "identifier": "language",
                                    "label": "Language",
                                },
                            ),
                            1: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"identifier": "code", "label": "Code"},
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("language", 0), ("code", 1)]],
                                {"help_text": "Code"},
                            ),
                            3: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Rich Text"},
                            ),
                        },
                        help_text="Question text",
                    ),
                ),
                (
                    "assignment",
                    modelcluster.fields.ParentalKey(
                        help_text="Question assignment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="assignments.assignment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
